// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwypwtfwfohiogmdbnvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eXB3dGZ3Zm9oaW9nbWRibnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDc1MjQsImV4cCI6MjA3MDY4MzUyNH0.fP4qswPkoNMl8HcHfV8v3Kr6DpkSHP3iOJTO6WMkWqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});